export type TUserId = number
export type ID = number
export type UserName = string
export type SchoolName = string

export enum ROLE {
  USER = "user",
  ADMIN = "admin"
}

export enum SCORE_TYPE {
  BEST_FIVE = "Best 5",
  BEST_SIX = "Best 6",
  GPA = "GPA"
}

export enum SCHOOL_TYPE {
  UNIVERSITY = "university",
  COLLEGE = "college",
  SECONDARY_SCHOOL = "secondary school"
}

export enum ADMISSION_TYPE {
  JUPAS = "Jupas",
  NON_JUPAS = "Non-jupas",
  BACHELOR = "Bachelor"
}

export enum ADMISSION_OFFER_TYPE {
  DIRECT = "Direct",
  CONDITIONAL = "Conditional"
}

export enum ADMISSION_LEVEL_TYPE {
  ONE = "Year 1",
  TWO = "Year 2",
  THREE = "Year 3",
  FOUR = "Year 4",
  FIVE = "Year 5",
  FIVE_PLUS = "Year 5+"
}

// export enum VOTE_TYPE {
//   LIKED = "like",
//   DISLIKE = "dislike"
// }

export interface ISelectMenuItemsType<T, U> {
  value: T
  title: U
}

export enum VoteTypeId {
  LIKED = 1,
  DISLIKE = -1
}

export enum DressCodeTypeId {
  FORMAL = 1,
  SMART_CASUAL,
  CASUAL,
  FREE
}

export enum SchoolTypeId {
  UNIVERSITY = 1,
  COLLEGE
}

export enum CurrentSchoolTypeId {
  UNIVERSITY = 1,
  COLLEGE,
  SECONDARY_SCHOOL,
  RETAKER,
  OTHER = 999
}

export enum ProgrammeTypeId {
  BACHELOR = 1,
  ASSOCIATE_DEGREE,
  HIGHER_DIPLOMA,
  PROFESSIONAL_DIPLOMA,
  FOUNDATION_DIPLOMA,
  ADVANCED_DIPLOMA,
  DIPLOMA
}

export enum ApplicationTypeId {
  JUPAS = 1,
  NON_JUPAS,
  BACHELOR,
  OTHER = 999
}

export enum DSEJupasChoicePriorityTypeId {
  BAND_A_ONE = 1,
  BAND_A_TWO,
  BAND_A_THREE,
  BAND_B,
  BAND_C,
  OTHER = 999
}

export enum AdmissionOfferTypeId {
  CONDITIONAL = 1,
  DIRECT
}

export enum InternshipTypeId {
  SUMMER = 1,
  WINTER,
  PLACEMENT
}

export enum AdmissionLevelTypeId {
  YEAR_ONE = 1,
  YEAR_TWO,
  YEAR_THREE,
  YEAR_FOUR,
  YEAR_FIVE_PLUS
}

export enum YearOfStudyTypeId {
  YEAR_ONE = 1,
  YEAR_TWO,
  YEAR_THREE,
  YEAR_FOUR,
  YEAR_FIVE_PLUS
}

export enum JobSourceTypeId {
  JIJIS = 1,
  LINKEDIN,
  INDEED,
  JOBSDB,
  COMPANY_WEBSITE,
  UNIVERSITY,
  INTERNAL_REFERRAL,
  OTHER = 999
}

export enum AcademicStatusTypeId {
  YEAR_ONE = 1,
  YEAR_TWO,
  YEAR_THERE,
  YEAR_FOUR,
  YEAR_FIVE_PLUS,
  POSTGRAD,
  ALUMI,
  OTHER = 999
}

export enum ContactMethodTypeId {
  EMAIL = 1,
  TELEGRAM,
  WHATSAPP,
  SIGNAL,
  OTHER
}
export enum HonorTypeId {
  FIRST = 1,
  SECOND_UP,
  SECOND_LOW,
  THIRD,
  SUMMA_CUM_LAUDE,
  MAGNA_CUM_LAUDE,
  CUM_LAUDE,
  PASS
}

export enum DSEGradeTypeId {
  ONE = 1,
  TWO,
  THREE,
  FOUR,
  FIVE,
  FIVE_START,
  FIVE_DOUBLE_STAR,
  PASS, //displat Text :達標/合格不
  FAIL, //displat Text :不達標/不合格
  UNCLASSIFIED
}

export enum DSESubjectId {
  CHINESE_LANGUAGE = 1,
  ENGLISH_LANGUAGE,
  MATHEMATICS_COMPULSORY_PART,
  CITIZENSHIP_AND_SOCIAL_DEVELOPMENT,
  LIBERAL_STUDIES,
  BIOLOGY,
  CHEMISTRY,
  ECONOMICS,
  BUSINESS_ACCOUNTING_AND_FINANCIAL_STUDIES,
  PHYSICS,
  GEOGRAPHY,
  M1,
  M2,
  CHINESE_HISTORY,
  INFORMATION_AND_COMMUNICATION_TECHNOLOGY,
  TOURISM_AND_HOSPITALITY_STUDIES,
  VISUAL_ARTS,
  CHINESE_LITERATURE,
  PHYSICAL_EDUCATION,
  HEALTH_MANAGEMENT_AND_SOCIAL_CARE,
  ETHICS_AND_RELIGIOUS_STUDIES,
  DESIGN_AND_APPLIED_TECHNOLOGY,
  COMBINED_SCIENCE,
  LITERATURE_IN_ENGLISH,
  TECHNOLOGY_AND_LIVING,
  MUSIC,
  INTEGRATED_SCIENCE
}

export enum JobCategoryTypeId {
  ARCHITECTURE = 1,
  ARTS_AND_CREATION,
  SERVICE_INDUSTRY,
  DESIGN,
  EDUCATION,
  ENGINEERING,
  ENVIRONMENT,
  FILM,
  BUSINESS,
  FOOD_AND_BEVERAGES,
  HEALTH,
  HUMAN_RESOURCE,
  INSURANCE,
  LEGAL_SERVICE,
  LOGISTIC,
  JEWELRY,
  MANAGEMENT,
  MANUFACTURE,
  MARKETING,
  MEDIA,
  MEDICAL_SERVICE,
  PRIMARY_INDUSTRY,
  PROPERTY,
  RETAIL,
  SCIENCE,
  SOCIAL_SERVICE,
  TEXTILES,
  TECHNOLOGY,
  TOURISM_AND_TRAVEL,
  TRANSLATION,
  UNCATEGORIZED,
  OTHER = 999
}

export enum JobTypeId {
  //Architecture
  ARCHITECTURE = 100,

  //Arts and creation
  ANIMATION = 200,
  ART,
  COMICS,
  CONTENT_CREATOR,
  ENTERTAINMENT,
  MUSIC,
  PERFORMER,
  WRITING_AND_EDITING,
  ARTS_AND_CREATION_OTHER = 299,

  //Service industry
  CUSTOMER_SERVICE = 300,
  SERVICE_INDUSTRY_OTHER = 399,

  //Design
  FASHION_DESIGN = 400,
  GRAPHICS_DESIGN,
  INTERIOR_DESIGN,
  PRODUCT_DESIGN,
  UXUI_DESIGN,
  DESIGN_OTHER = 499,

  //Education
  KINDERGARTEN_TEACHER = 500,
  LECTURER_OR_PROFESSOR,
  PRIMARY_SCHOOL_TEACHER,
  SECONDARY_SCHOOL_TEACHER,
  TUTOR,
  EDUCATION_OTHER = 599,

  //Engineering
  BUILDING_SERVICES_ENGINEERING = 600,
  CIVIL_AND_STRUCTURAL_ENGINEERING,
  CHEMICAL_ENGINEERING,
  DRAFTSMAN,
  ELECTRICAL_ENGINEERING,
  ELECTRONIC_ENGINEERING,
  MECHANICAL_ENGINEERING,
  NETWORK_ENGINEERING,
  SEMICONDUCTOR_ENGINEERING,
  SURVEYING,
  TECHNICIAN,
  ENGINEERING_OTHER = 699,

  //Environment
  CONSERVATION = 700,
  RECYCLING,
  ENVIRONMENT_OTHER = 799,

  //Film
  DIRECTOR = 800,
  FILM_PRODUCTION,
  LIGHTING_TECHNICIAN,
  SOUND_TECHNICIAN,
  FILM_OTHER = 899,

  //Business
  ACCOUNTING = 900,
  AUDIT,
  BANKING,
  BUSINESS_ANALYST,
  BUSINESS_DEVELOPMENT,
  FINANCE,
  BUSINESS_OTHER = 999,

  //Food and Beverages
  CHEF = 1000,
  COFFEE,
  DESSERT,
  LIQUOR,
  FOOD_AND_BEVERAGES_OTHER = 1099,

  //Health
  BEAUTY_COSMETICS = 1100,
  HEALTH_CARE,
  SPORT,
  HEALTH_OTHER = 1199,

  // Human Resource
  STAFFING_AND_RECRUITING = 1200,
  RECRUITMENT_CONSULTANT,
  HUMAN_RESOURCE_OTHER = 1299,

  //Insurance
  INSURANCE = 1300,

  //Legal
  BARRISTER = 1400,
  LEGAL_TRAINEE,
  LEGAL_CONSULTANT,
  SOLICITOR,
  LEGAL_SERVICE_OTHER = 1499,

  //Logistic
  TRANSPORTATION_AND_LOGISTIC = 1500,

  //
  LUXURY_GOODS_AND_JEWELRY = 1600,

  // Management
  PROJECT_MANAGER = 1700,
  PRODUCT_MANAGER,
  MANAGEMENT_TRAINEE,
  MANAGEMENT_OTHER = 1799,

  // Manufacturing
  HANDICRAFT = 1800,
  MANUFACTURING_OTHER = 1899,

  // Marketing
  ADVERTISING = 1900,
  DIGITAL_MARKETING,
  MARKETING,
  MARKETING_OTHER = 1999,

  //Media
  BROADCASTING = 2000,
  MEDIA_PRODUCTION,
  MULTI_MEDIA,
  EDITOR_AND_JOURNALISM,
  MEDIA_OTHER = 2099,

  //Medic
  DENTAL_SERVICE = 2100,
  DOCTOR,
  MUSIC_THERAPIST,
  NURSE,
  NURSING,
  OCCUPATIONAL_THERAPIST,
  PHARMACY,
  PSYCHOLOGICAL_COUNSELLING,
  PHYSICAL_THERAPIST,
  SPEECH_THERAPIST,
  THERAPIST,
  VETERINARY,

  MEDICAL_SERVICE_OTHER = 2199,

  // Primary industry
  AGRICULTURE = 2200,
  FISHERY,

  PRIMARY_INDUSTRY_OTHER = 2299,

  //Property
  REAL_ESTATE = 2300,
  PROPERTY_MANAGEMENT,
  PROPERTY_OTHER = 2399,

  //Retail
  MERCHANDISING = 2400,
  PURCHASING,
  RETAIL_OTHER = 2499,

  //Science
  ENERGY = 2500,
  DIETITIAN,
  FOOD_NUTRITIONIST,
  FOOD_SCIENCE,
  LABORATORY,
  R_AND_D,
  SCIENCE_OTHER = 2599,

  //Social service
  SOCIAL_WORKER = 2600,
  SOCIAL_SERVICE_OTHER = 2699,

  //TEXTILES
  TEXTILES = 2700, // INFORMATION_TECHNOLOGY_AND_SERVICES,

  //Technology
  AI_AND_MACHINE_LEARNING_ENGINEER = 2800,
  BACKEND_SOFTWARE_ENGINEER,
  CYBER_SECURITY,
  FRONTEND_SOFTWARE_ENGINEER,
  DEV_OPS,
  DATA_ANALYST,
  DATA_SCIENTIST,
  GAME_DEVELOPER,
  MOBILE_SOFTWARE_ENGINEER,
  INFRASTRUCTURE_ENGINEER,
  IOT_ENGINEER,
  IT_SUPPORT,
  QA_ENGINEER,
  ROBOTIC_ENGINEER,
  SOLUTION_ENGINEER,
  FULL_STACK_SOFTWARE_ENGINEER,
  TECHNOLOGY_OTHER = 2899,

  //TOURISM and travel
  TRAVEL = 2900,
  HOTEL_SERVICE,
  TOURISM_OTHER = 2999,

  //Translation
  TRANSLATION = 3000,

  //UNCATEGORIZED
  CIVIL_SERVANT = 3100,
  ENTREPRENEUR,
  FREELANCER,
  KOL,
  SLASHER,

  //Other
  OTHER = 99999
}

//sorting
export enum SchoolSortingTypes {
  POST_DATE_ASCENDING = "createdAt,ASC",
  POST_DATE_DESCENDING = "createdAt,DESC",
  ADMISSION_DATE_ASCENDING = "admissionDate,ASC",
  ADMISSION_DATE_DESCENDING = "admissionDate,DESC",
  VOTE_ASCENDING = "vote,ASC",
  VOTE_DESCENDING = "vote,DESC",
  RECOMMENDATION_ASCENDING = "recommendation,ASC",
  RECOMMENDATION_DESCENDING = "recommendation,DESC"
}

export enum ProgrammeSortingTypes {
  POST_DATE_ASCENDING = "createdAt,ASC",
  POST_DATE_DESCENDING = "createdAt,DESC",
  ADMISSION_DATE_ASCENDING = "admissionDate,ASC",
  ADMISSION_DATE_DESCENDING = "admissionDate,DESC",
  VOTE_ASCENDING = "vote,ASC",
  VOTE_DESCENDING = "vote,DESC",
  RECOMMENDATION_ASCENDING = "recommendation,ASC",
  RECOMMENDATION_DESCENDING = "recommendation,DESC"
}

export enum InterviewSortingTypes {
  POST_DATE_ASCENDING = "createdAt,ASC",
  POST_DATE_DESCENDING = "createdAt,DESC",
  INTERVIEW_DATE_ASCENDING = "interviewDate,ASC",
  INTERVIEW_DATE_DESCENDING = "interviewDate,DESC",
  VOTE_ASCENDING = "vote,ASC",
  VOTE_DESCENDING = "vote,DESC",
  DIFFICULTY_ASCENDING = "difficulty,ASC",
  DIFFICULTY_DESCENDING = "difficulty,DESC",
  BESTFIVE_ASCENDING = "bestFive,ASC",
  BESTFIVE_DESCENDING = "bestFive,DESC",
  BESTSIX_ASCENDING = "bestSix,ASC",
  BESTSIX_DESCENDING = "bestSix,DESC",
  GPA_ASCENDING = "gpa,ASC",
  GAP_DESCENDING = "gpa,DESC"
}

export enum admissionOfferSortingTypes {
  POST_DATE_ASCENDING = "createdAt,ASC",
  POST_DATE_DESCENDING = "createdAt,DESC",
  OFFER_RECEIVED_DATE_ASCENDING = "offerReceivedDate,ASC",
  OFFER_RECEIVED_DATE_DESCENDING = "offerReceivedDate,DESC",
  VOTE_ASCENDING = "vote,ASC",
  VOTE_DESCENDING = "vote,DESC",
  BESTFIVE_ASCENDING = "bestFive,ASC",
  BESTFIVE_DESCENDING = "bestFive,DESC",
  BESTSIX_ASCENDING = "bestSix,ASC",
  BESTSIX_DESCENDING = "bestSix,DESC",
  GPA_ASCENDING = "gpa,ASC",
  GAP_DESCENDING = "gpa,DESC"
}

export enum InternshipOfferSortingTypes {
  POST_DATE_ASCENDING = "createdAt,ASC",
  POST_DATE_DESCENDING = "createdAt,DESC",
  OFFER_RECEIVED_DATE_ASCENDING = "offerReceivedDate,ASC",
  OFFER_RECEIVED_DATE_DESCENDING = "offerReceivedDate,DESC",
  VOTE_ASCENDING = "vote,ASC",
  VOTE_DESCENDING = "vote,DESC",
  DIFFICULTY_ASCENDING = "difficulty,ASC",
  DIFFICULTY_DESCENDING = "difficulty,DESC",
  SALARY_ASCENDING = "salary,ASC",
  SALARY_DESCENDING = "salary,DESC"
}

export enum gradJobOfferSortingTypes {
  POST_DATE_ASCENDING = "createdAt,ASC",
  POST_DATE_DESCENDING = "createdAt,DESC",
  OFFER_RECEIVED_DATE_ASCENDING = "offerReceivedDate,ASC",
  OFFER_RECEIVED_DATE_DESCENDING = "offerReceivedDate,DESC",
  VOTE_ASCENDING = "vote,ASC",
  VOTE_DESCENDING = "vote,DESC",
  DIFFICULTY_ASCENDING = "difficulty,ASC",
  DIFFICULTY_DESCENDING = "difficulty,DESC",
  HOPE_ASCENDING = "hope,ASC",
  HOPE_DESCENDING = "hope,DESC",
  SALARY_ASCENDING = "salary,ASC",
  SALARY_DESCENDING = "salary,DESC"
}
