export const uni = [
  {
    id: "1",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 1,
  },
  {
    id: "9",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 1,
  },
  {
    id: "2",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 2,
  },
  {
    id: "3",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 3,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },

  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
  {
    id: "4",
    schoolChineseName: "香港科技大學",
    schoolEnglishName: "Hong Kong University of Science and Technology",
    shortName: "HKUST",
    averageSchoolScore: 4,
  },
];

export const college = [
  {
    id: "1",
    schoolChineseName: "香港專業教育學院",
    schoolEnglishName: "Hong Kong Institute of Vocational Education",
    shortName: "IVE",
    averageSchoolScore: 2,
  },
  {
    id: "1",
    schoolChineseName: "香港專業教育學院",
    schoolEnglishName: "Hong Kong Institute of Vocational Education",
    shortName: "IVE",
    averageSchoolScore: 5,
  },
  {
    id: "2",
    schoolChineseName: "香港專業教育學院",
    schoolEnglishName: "Hong Kong Institute of Vocational Education",
    shortName: "IVE",
    averageSchoolScore: 4,
  },
  {
    id: "3",
    schoolChineseName: "香港專業教育學院",
    schoolEnglishName: "Hong Kong Institute of Vocational Education",
    shortName: "IVE",
    averageSchoolScore: 3,
  },
  {
    id: "4",
    schoolChineseName: "香港專業教育學院",
    schoolEnglishName: "Hong Kong Institute of Vocational Education",
    shortName: "IVE",
    averageSchoolScore: 2,
  },
];
